from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin-login/', views.admin_login, name='admin_login'),
    path('constructor/', views.constructor, name='constructor'),
    path('favorites/', views.favorites, name='favorites'),
    path('create_order/', views.create_order, name='create_order'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('kitchen/', views.kitchen, name='kitchen'),
    path('api/update_status/<int:order_id>/', views.update_status, name='update_status'),
    path('courier/', views.courier_view, name='courier'),
    path('init_data/', views.init_data, name='init_data'),
    path('cart/', views.cart_view, name='cart'),
    path('api/add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('api/remove-from-cart/', views.remove_from_cart, name='remove_from_cart'),
    path('api/update-cart/', views.update_cart_quantity, name='update_cart'),
    path('api/optimize-route/', views.optimize_route_api, name='optimize_route'),
    path('check-route/', views.check_route_page, name='check_route_page'),
    path('api/config/', views.get_config_api, name='get_config'),
    path('api/order/<int:order_id>/status/', views.get_order_status, name='get_order_status'),
    path('api/cart-count/', views.get_cart_count, name='get_cart_count'),
    path('order/<int:order_id>/track/', views.order_tracking, name='order_tracking'),
    path('order/<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
    path('courier/<int:courier_id>/assign/', views.assign_courier_to_order, name='assign_courier'),
    path('reports/sales/', views.sales_report, name='sales_report'),
    path('reports/popular-pizzas/', views.popular_pizzas_report, name='popular_pizzas'),
    path('favorites/remove/<int:pizza_id>/', views.remove_from_favorites, name='remove_from_favorites'),
    path('admin-notifications/', views.notifications_view, name='notifications'),
]